"""Tests for ProvisionService and ProvisionData schema."""

import json

import httpx
import pytest
from connhex._base_client import ConnhexClient
from connhex.provision import ProvisionData, ProvisionService
from pydantic import ValidationError


def _make_client(handler) -> ConnhexClient:
    client = ConnhexClient(
        instance_url="https://example.test",
        token="t",
        max_retries=0,
    )
    client._http = httpx.AsyncClient(
        transport=httpx.MockTransport(handler),
        follow_redirects=True,
    )
    return client


def test_provision_data_init_id_required() -> None:
    with pytest.raises(ValidationError):
        ProvisionData(init_id="")


def test_provision_data_init_key_autogenerated() -> None:
    pd = ProvisionData(init_id="SN123")
    assert pd.init_key
    assert len(pd.init_key) == 36  # str(uuid4())


def test_provision_data_invalid_model() -> None:
    with pytest.raises(ValidationError):
        ProvisionData(init_id="SN1", model="not-a-uuid")


def test_provision_data_valid_model() -> None:
    pd = ProvisionData(
        init_id="SN1", model="123e4567-e89b-12d3-a456-426614174000"
    )
    assert pd.model == "123e4567-e89b-12d3-a456-426614174000"


def test_provision_data_quota_string_coerced() -> None:
    pd = ProvisionData.model_validate(
        {"init_id": "SN1", "migration_key_quota": "5"}
    )
    assert pd.migration_key_quota == 5


@pytest.mark.asyncio
async def test_bulk_provision_posts_array() -> None:
    captured: dict = {}

    def handler(request: httpx.Request) -> httpx.Response:
        captured["url"] = str(request.url)
        captured["body"] = json.loads(request.content)
        return httpx.Response(
            201,
            json={
                "things": [
                    {"id": "t1", "name": "n1", "key": "k1"},
                    {"id": "t2", "name": "n2", "key": "k2"},
                ],
                "processed": 2,
                "failed": 0,
                "errors": [],
            },
        )

    client = _make_client(handler)
    svc = ProvisionService(client)
    items = [ProvisionData(init_id="A"), ProvisionData(init_id="B")]
    result = await svc.bulk_provision(items)

    assert captured["url"].endswith("/iot/provision/things/bulk")
    assert isinstance(captured["body"], list)
    assert len(captured["body"]) == 2
    assert captured["body"][0]["init_id"] == "A"
    assert result.processed == 2
    assert [t.id for t in result.things] == ["t1", "t2"]


@pytest.mark.asyncio
async def test_bulk_unprovision_sends_ids() -> None:
    captured: dict = {}

    def handler(request: httpx.Request) -> httpx.Response:
        captured["method"] = request.method
        captured["body"] = json.loads(request.content)
        return httpx.Response(204)

    client = _make_client(handler)
    svc = ProvisionService(client)
    await svc.bulk_unprovision(["a", "b", "c"])

    assert captured["method"] == "DELETE"
    assert captured["body"] == ["a", "b", "c"]
