# ==============================================================================
# @generated by connhex-sdk/scripts/generate_sync.py
# from the corresponding async source in connhex/aio/.
#
# Any changes made to this file will be overwritten when the script runs again.
# Please edit the async file instead.
# ==============================================================================

from connhex.sync.auth import password_login

__all__ = ["password_login"]
