# ==============================================================================
# @generated by connhex-sdk/scripts/generate_sync.py
# from the corresponding async source in connhex/aio/.
#
# Any changes made to this file will be overwritten when the script runs again.
# Please edit the async file instead.
# ==============================================================================

import random
from time import sleep as _sleep
from datetime import datetime, timezone
from email.utils import parsedate_to_datetime
from typing import Callable

import httpx

from connhex import __version__
from connhex.auth import Auth, BearerAuth, SessionCookieAuth
from connhex.errors import (
    APIConnectionError,
    APITimeoutError,
    raise_for_connhex_response,
)
from connhex.urls import build_url

TIMEOUT = 30.0
MAX_RETRIES = 2
RETRY_INITIAL = 0.5
RETRY_CAP = 8.0
RETRY_JITTER = 0.25
RETRY_STATUSES = frozenset({408, 429, 500, 502, 503, 504})

SyncTokenProvider = Callable[[], str]
SyncAuthProvider = Callable[[], Auth]


def _retry_after_seconds(resp: httpx.Response) -> float | None:
    """Parse a Retry-After header. Returns None if absent or unparseable."""
    value = resp.headers.get("Retry-After")
    if not value:
        return None
    try:
        return max(0.0, float(value))
    except ValueError:
        pass
    try:
        when = parsedate_to_datetime(value)
        if when.tzinfo is None:
            when = when.replace(tzinfo=timezone.utc)
        return max(0.0, (when - datetime.now(timezone.utc)).total_seconds())
    except (TypeError, ValueError):
        return None


class ConnhexClient:
    """HTTP client for the Connhex API.

    Auth is provided with a static `token`, a per-request `token_provider`,
    or an `auth_provider` that resolves either bearer or session-cookie auth.

    Transient failures (network errors and HTTP 429/5xx) are retried with
    exponential backoff + jitter, honoring `Retry-After` when present.
    Set `max_retries=0` to disable retries.
    """

    def __init__(
        self,
        *,
        instance_url: str,
        token: str | None = None,
        token_provider: SyncTokenProvider | None = None,
        auth_provider: SyncAuthProvider | None = None,
        timeout: float = TIMEOUT,
        max_retries: int = MAX_RETRIES,
        retry_initial: float = RETRY_INITIAL,
        retry_cap: float = RETRY_CAP,
    ):
        self._validate_auth(token, token_provider, auth_provider)
        self.instance_url = instance_url.rstrip("/")
        self._token = token
        self._token_provider = token_provider
        self._auth_provider = auth_provider
        self._max_retries = max_retries
        self._retry_initial = retry_initial
        self._retry_cap = retry_cap
        self._user_agent = (
            f"connhex-python/{__version__} httpx/{httpx.__version__}"
        )
        self._http = httpx.Client(
            timeout=httpx.Timeout(timeout),
            follow_redirects=True,
        )

    def _validate_auth(
        self,
        token: str | None,
        token_provider: SyncTokenProvider | None,
        auth_provider: SyncAuthProvider | None,
    ) -> None:
        if (
            sum(
                value is not None
                for value in (token, token_provider, auth_provider)
            )
            != 1
        ):
            raise ValueError(
                "exactly one of `token`, `token_provider`, or `auth_provider` is required"
            )

    def _auth_headers(self) -> dict[str, str]:
        if self._auth_provider is not None:
            auth = self._auth_provider()
            if isinstance(auth, BearerAuth):
                return {"Authorization": f"Bearer {auth.token}"}
            if isinstance(auth, SessionCookieAuth):
                return {"Cookie": f"chx_auth_session={auth.value}"}
            raise TypeError(f"unsupported authentication credential: {auth!r}")

        if self._token_provider is not None:
            token = self._token_provider()
        else:
            assert self._token is not None
            token = self._token
        return {"Authorization": f"Bearer {token}"}

    def _backoff(self, attempt: int) -> float:
        delay = min(self._retry_initial * (2**attempt), self._retry_cap)
        return delay + random.uniform(0, RETRY_JITTER)

    def request(
        self,
        method: str,
        path: str,
        *,
        base: str = "apis",
        extra_headers: dict[str, str] | None = None,
        timeout: float | None = None,
        **kwargs,
    ) -> httpx.Response:
        url = f"{build_url(self.instance_url, base)}{path}"
        headers = {
            "Accept": "application/json",
            "User-Agent": self._user_agent,
            **self._auth_headers(),
            **(extra_headers or {}),
        }
        if timeout is not None:
            kwargs["timeout"] = httpx.Timeout(timeout)

        for attempt in range(self._max_retries + 1):
            try:
                resp = self._http.request(
                    method, url, headers=headers, **kwargs
                )
            except httpx.TimeoutException as e:
                if attempt == self._max_retries:
                    raise APITimeoutError(
                        f"Request timed out: {e}", cause=e
                    ) from e
                _sleep(self._backoff(attempt))
                continue
            except httpx.RequestError as e:
                if attempt == self._max_retries:
                    raise APIConnectionError(
                        f"Network error: {e}", cause=e
                    ) from e
                _sleep(self._backoff(attempt))
                continue

            if (
                resp.status_code in RETRY_STATUSES
                and attempt < self._max_retries
            ):
                delay = _retry_after_seconds(resp)
                if delay is None:
                    delay = self._backoff(attempt)
                _sleep(delay)
                continue

            raise_for_connhex_response(resp)
            return resp

        # Unreachable: loop always returns or raises.
        raise APIConnectionError("retry loop exhausted")

    def close(self) -> None:
        self._http.close()
