# ==============================================================================
# @generated by connhex-sdk/scripts/generate_sync.py
# from the corresponding async source in connhex/aio/.
#
# Any changes made to this file will be overwritten when the script runs again.
# Please edit the async file instead.
# ==============================================================================

import os

from connhex.sync._base_client import (
    MAX_RETRIES,
    TIMEOUT,
    ConnhexClient,
    SyncTokenProvider,
)
from connhex.sync.services.iam import IAMService
from connhex.sync.services.models import ModelsService
from connhex.sync.services.provision import ProvisionService
from connhex.sync.services.reader import ReaderService
from connhex.sync.services.resources import ResourcesService
from connhex.sync.services.rules_engine import RulesEngineService
from connhex.sync.services.things import ThingsService
from connhex.urls import DEFAULT_INSTANCE_URL

ENV_INSTANCE_URL = "CONNHEX_INSTANCE_URL"
ENV_TOKEN = "CONNHEX_BEARER_TOKEN"


class Connhex:
    """Sync client for the Connhex API.

    This is the entry point of the SDK. One `Connhex` instance owns a
    single underlying HTTP client and exposes every Connhex service as an
    attribute:

        ```python
        from connhex import Connhex

        with Connhex(
            token="<personal access token>",
        ) as connhex:
            me = connhex.iam.whoami()
            things = connhex.things.list(limit=20)
            thing = connhex.things.get("thing-id")
        ```

    Authentication. Pass exactly one of:

    - `token`: a static bearer token (personal access token). If omitted,
      the `CONNHEX_BEARER_TOKEN` environment variable is used.
    - `token_provider`: sync callable returning a fresh token on every
      request — for multi-user servers or short-lived tokens.

    `instance_url` falls back to the `CONNHEX_INSTANCE_URL` environment
    variable when omitted, then to the Connhex SaaS instance at
    `https://connhex.com`.

    Lifecycle. Always close the client to release the underlying connection
    pool. The recommended form is `with Connhex(...) as c: ...`;
    if you can't use a context manager, call `c.close()` explicitly.

    Retries. Transient failures (network errors, HTTP 408/429/5xx) are
    retried with exponential backoff and jitter, honoring `Retry-After` when
    the server sends it. Set `max_retries=0` to disable.

    Args:
        instance_url: Base URL of your Connhex tenant, e.g.
            `"https://your-tenant.connhex.com"`. Falls back to
            `$CONNHEX_INSTANCE_URL`, then `https://connhex.com`.
        token: Static bearer token. Falls back to `$CONNHEX_BEARER_TOKEN`.
            Mutually exclusive with `token_provider`.
        token_provider: Sync callable resolving a bearer token per request.
            Mutually exclusive with `token`.
        timeout: Default per-request timeout in seconds.
        max_retries: Max retries for transient failures (0 disables).
    """

    def __init__(
        self,
        *,
        instance_url: str | None = None,
        token: str | None = None,
        token_provider: SyncTokenProvider | None = None,
        timeout: float = TIMEOUT,
        max_retries: int = MAX_RETRIES,
    ) -> None:
        instance_url = (
            instance_url
            or os.environ.get(ENV_INSTANCE_URL)
            or DEFAULT_INSTANCE_URL
        )
        if token is None and token_provider is None:
            token = os.environ.get(ENV_TOKEN)

        self._http = ConnhexClient(
            instance_url=instance_url,
            token=token,
            token_provider=token_provider,
            timeout=timeout,
            max_retries=max_retries,
        )
        self.things = ThingsService(self._http)
        self.models = ModelsService(self._http)
        self.rules = RulesEngineService(self._http)
        self.iam = IAMService(self._http)
        self.reader = ReaderService(self._http)
        self.provision = ProvisionService(self._http)
        self.resources = ResourcesService(self._http, "resources")
        self.manufacturing = ResourcesService(self._http, "manufacturing")

    def close(self) -> None:
        self._http.close()

    def __enter__(self) -> "Connhex":
        return self

    def __exit__(self, exc_type, exc, tb) -> None:
        self.close()
