# ==============================================================================
# @generated by connhex-sdk/scripts/generate_sync.py
# from the corresponding async source in connhex/aio/.
#
# Any changes made to this file will be overwritten when the script runs again.
# Please edit the async file instead.
# ==============================================================================

from connhex.sync._base_client import ConnhexClient


class IAMService:
    def __init__(self, client: ConnhexClient):
        self.client = client

    def whoami(self) -> dict:
        resp = self.client.request(
            "GET", "/auth/sessions/whoami", base="accounts"
        )
        return resp.json()

    def get_identity_schemas(self) -> list:
        resp = self.client.request("GET", "/auth/schemas", base="accounts")
        return resp.json()
