# ==============================================================================
# @generated by connhex-sdk/scripts/generate_sync.py
# from the corresponding async source in connhex/aio/.
#
# Any changes made to this file will be overwritten when the script runs again.
# Please edit the async file instead.
# ==============================================================================

from connhex.sync._base_client import ConnhexClient
from connhex.schemas.models import Model, ModelsPage
from connhex.schemas.things import ThingsPage


class ModelsService:
    def __init__(self, client: ConnhexClient):
        self.client = client

    def get(self, model_id: str) -> Model:
        resp = self.client.request("GET", f"/iot/models/{model_id}")
        return Model.model_validate(resp.json())

    def list(
        self,
        *,
        limit: int = 10,
        offset: int = 0,
        name: str | None = None,
        order: str | None = None,
        dir: str | None = None,
        tag: str | None = None,
        tenant: str | None = None,
    ) -> ModelsPage:
        params: dict = {"limit": limit, "offset": offset}
        if name is not None:
            params["name"] = name
        if order is not None:
            params["order"] = order
        if dir is not None:
            params["dir"] = dir
        if tag is not None:
            params["tag"] = tag
        if tenant is not None:
            params["tenant"] = tenant
        resp = self.client.request("GET", "/iot/models", params=params)
        return ModelsPage.model_validate(resp.json())

    def get_things(
        self,
        model_id: str,
        *,
        limit: int = 10,
        offset: int = 0,
        order: str | None = None,
        dir: str | None = None,
    ) -> ThingsPage:
        params: dict = {"limit": limit, "offset": offset}
        if order is not None:
            params["order"] = order
        if dir is not None:
            params["dir"] = dir
        resp = self.client.request(
            "GET", f"/iot/models/{model_id}/things", params=params
        )
        return ThingsPage.model_validate(resp.json())
