# ==============================================================================
# @generated by connhex-sdk/scripts/generate_sync.py
# from the corresponding async source in connhex/aio/.
#
# Any changes made to this file will be overwritten when the script runs again.
# Please edit the async file instead.
# ==============================================================================

from connhex.sync._base_client import ConnhexClient
from connhex.schemas.provision import BulkResult, ProvisionData


class ProvisionService:
    def __init__(self, client: ConnhexClient):
        self.client = client

    def bulk_provision(self, items: list[ProvisionData]) -> BulkResult:
        payload = [item.model_dump(exclude_none=True) for item in items]
        resp = self.client.request(
            "POST",
            "/iot/provision/things/bulk",
            json=payload,
            extra_headers={"Content-Type": "application/json"},
        )
        return BulkResult.model_validate(resp.json())

    def bulk_unprovision(self, thing_ids: list[str]) -> None:
        self.client.request(
            "DELETE",
            "/iot/provision/things/bulk",
            json=thing_ids,
            extra_headers={"Content-Type": "application/json"},
        )
