# ==============================================================================
# @generated by connhex-sdk/scripts/generate_sync.py
# from the corresponding async source in connhex/aio/.
#
# Any changes made to this file will be overwritten when the script runs again.
# Please edit the async file instead.
# ==============================================================================

import time

from connhex.sync._base_client import ConnhexClient
from connhex._jsonapi import build_filter_params, flatten_response
from connhex.schemas.resources import ListResponse, Resource

_SCHEMA_TTL_SECONDS = 7 * 24 * 3600
_DEFAULT_HEADERS = {"Accept": "application/vnd.api+json"}


class ResourcesService:
    def __init__(self, client: ConnhexClient, base_url: str):
        self.base_url = base_url
        self.client = client
        self._schema_cache: tuple[float, dict] | None = None
        self._schema_ttl: float = _SCHEMA_TTL_SECONDS

    def get_schema(self) -> dict:
        """
        Fetch the resource schema for this service. Cached per instance with a
        long TTL (schemas are not expected to change while the service is live).
        """
        cached = self._schema_cache
        if (
            cached is not None
            and (time.monotonic() - cached[0]) < self._schema_ttl
        ):
            return cached[1]
        resp = self.client.request(
            "GET",
            f"/{self.base_url}/schema",
            extra_headers=_DEFAULT_HEADERS,
        )
        data = resp.json()

        self._schema_cache = (time.monotonic(), data)
        return data

    def list(
        self,
        resource_type: str,
        *,
        filter: dict | None = None,
        sort: str | None = None,
        include: str | None = None,
        fields: dict | None = None,
        page_limit: int = 25,
        page_offset: int = 0,
    ) -> ListResponse[Resource]:
        params: dict = {
            "page[limit]": page_limit,
            "page[offset]": page_offset,
        }
        if sort:
            params["sort"] = sort
        if include:
            params["include"] = include
        if fields:
            for type_name, field_list in fields.items():
                params[f"fields[{type_name}]"] = field_list
        if filter:
            params.update(build_filter_params(filter))

        resp = self.client.request(
            "GET",
            f"/{self.base_url}/{resource_type}",
            params=params,
            extra_headers=_DEFAULT_HEADERS,
        )
        return ListResponse[Resource].model_validate(
            flatten_response(resp.json())
        )

    def get(
        self,
        resource_type: str,
        ids: str,
        include: str | None = None,
    ) -> Resource:
        params = {}
        if include:
            params["include"] = include
        resp = self.client.request(
            "GET",
            f"/{self.base_url}/{resource_type}/{ids}",
            params=params,
            extra_headers=_DEFAULT_HEADERS,
        )
        return Resource.model_validate(flatten_response(resp.json())["data"])

    def create(self, resource_type: str, data: dict) -> Resource:
        resp = self.client.request(
            "POST",
            f"/{self.base_url}/{resource_type}",
            json=data,
            extra_headers={
                "Content-Type": "application/vnd.api+json",
                **_DEFAULT_HEADERS,
            },
        )
        return Resource.model_validate(flatten_response(resp.json())["data"])

    def update(self, resource_type: str, ids: str, data: dict) -> Resource:
        resp = self.client.request(
            "PATCH",
            f"/{self.base_url}/{resource_type}/{ids}",
            json=data,
            extra_headers={
                "Content-Type": "application/vnd.api+json",
                **_DEFAULT_HEADERS,
            },
        )
        return Resource.model_validate(flatten_response(resp.json())["data"])

    def delete(self, resource_type: str, ids: str) -> None:
        self.client.request("DELETE", f"/{self.base_url}/{resource_type}/{ids}")
