"""Generate connhex/sync/ from connhex/aio/.

Single source of truth: hand-written async code lives in `aio/`. This script
runs unasync to emit sync siblings into `sync/`.
"""

from __future__ import annotations

import glob
import os
import subprocess
import sys

import unasync

REPO_ROOT = os.path.abspath(
    os.path.join(os.path.dirname(__file__), "..", "..", "..")
)
SOURCE_DIR = os.path.join(
    REPO_ROOT, "packages", "connhex-sdk", "src", "connhex", "aio"
)
TARGET_DIR = os.path.join(
    REPO_ROOT, "packages", "connhex-sdk", "src", "connhex", "sync"
)

# unasync substitutes single identifier tokens.
TOKEN_REPLACEMENTS = {
    "AsyncConnhex": "Connhex",
    "TokenProvider": "SyncTokenProvider",
    "AsyncClient": "Client",
    "aclose": "close",
    "__aenter__": "__enter__",
    "__aexit__": "__exit__",
}

BANNER = """\
# ==============================================================================
# @generated by connhex-sdk/scripts/generate_sync.py
# from the corresponding async source in connhex/aio/.
#
# Any changes made to this file will be overwritten when the script runs again.
# Please edit the async file instead.
# ==============================================================================

"""


SUBSTRING_REPLACEMENTS = [
    ("Awaitable[str]", "str"),
    (
        "from asyncio import sleep as _sleep",
        "from time import sleep as _sleep",
    ),
    # Sibling-package import rewrite. unasync's Rule rewrites file paths but
    # not dotted module names inside import statements.
    ("connhex.aio.", "connhex.sync."),
    # Docstring / comment rewrites.
    ("AsyncConnhex", "Connhex"),
    ("async with ", "with "),
    ("await ", ""),
    ("Async client", "Sync client"),
    ("async callable", "sync callable"),
    ("Async callable", "Sync callable"),
]


def _post_process(path: str) -> None:
    with open(path) as fh:
        text = fh.read()
    new = text
    for old, repl in SUBSTRING_REPLACEMENTS:
        new = new.replace(old, repl)
    # Drop `Awaitable` from `typing` imports if it's now unused. `Awaitable`
    # only appeared in the `TokenProvider` alias; once that becomes `str` the
    # import is dead. After substring substitution above, the only remaining
    # occurrence should be on the typing import line itself.
    if new.count("Awaitable") == 1:
        new = new.replace("Awaitable, ", "").replace(", Awaitable", "")
    if not new.startswith(BANNER):
        new = BANNER + new
    if new != text:
        with open(path, "w") as fh:
            fh.write(new)


def main() -> int:
    files = sorted(
        glob.glob(os.path.join(SOURCE_DIR, "**", "*.py"), recursive=True)
    )
    if not files:
        print(f"no python files found under {SOURCE_DIR}", file=sys.stderr)
        return 1

    unasync.unasync_files(
        files,
        rules=[
            unasync.Rule(
                fromdir="/connhex/aio/",
                todir="/connhex/sync/",
                additional_replacements=TOKEN_REPLACEMENTS,
            ),
        ],
    )
    generated = sorted(
        glob.glob(os.path.join(TARGET_DIR, "**", "*.py"), recursive=True)
    )
    for path in generated:
        _post_process(path)

    # Run ruff format so the generated tree matches repository style; without
    # this, the CI drift guard would falsely report changes after a fresh
    # generation on a developer machine.
    subprocess.run(
        ["uv", "run", "ruff", "format", "--quiet", TARGET_DIR],
        check=True,
    )
    print(f"generated sync code for {len(files)} files in {TARGET_DIR}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
